nameOverride: example-go-service

image:
  repository: registry.gitlab.com/gnexlayer/example-go-service/example-go-service
  tag: v0.0.0

replicaCount: 3

env:
  LOG_LEVEL: warn
  DEBUG: "false"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

pdb:
  enabled: true
  minAvailable: 2

