apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gnexlayer-services
  namespace: argocd
spec:
  description: GNexLayer service deployments
  sourceRepos:
    - 'https://gitlab.com/gnexlayer/gitops-config.git'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

